# Generated by Django 4.1.4 on 2022-12-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tour1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
