# Generated by Django 4.1.4 on 2022-12-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transaction_tour1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.CharField(max_length=300),
        ),
    ]
