# Generated by Django 4.1.4 on 2022-12-30 13:42

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mytours_payment_date_mytours_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytours',
            options={},
        ),
        migrations.RemoveField(
            model_name='mytours',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='mytours',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='mytours',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='mytours',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mytours',
            name='tour',
        ),
        migrations.AddField(
            model_name='mytours',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='english',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='mytours',
            name='extra_img_five',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/extra/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='extra_img_four',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/extra/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='extra_img_one',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/extra/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='extra_img_three',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/extra/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='extra_img_two',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/extra/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='image_uz',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, scale=None, size=[1920, 1080], upload_to='tours/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='russian',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='mytours',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='uzbek',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='mytours',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tours/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='tours/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mytours',
            name='video_uz',
            field=models.FileField(blank=True, null=True, upload_to='tours/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])]),
        ),
        migrations.AddField(
            model_name='mytours',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
