# Generated by Django 4.1.4 on 2022-12-30 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mytours_options_remove_mytours_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytours',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytours',
            name='payment_status',
            field=models.CharField(choices=[('new', 'Yangi'), ('paid', "To'landi"), ('canceled', 'Bekor qilindi')], default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytours',
            name='payment_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
