# Generated by Django 4.1.4 on 2022-12-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mytours_payment_date_mytours_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytours',
            options={'verbose_name': 'My Tours', 'verbose_name_plural': 'My Tours'},
        ),
    ]
