# Generated by Django 4.1.4 on 2022-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_mytours_date_remove_mytours_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytours',
            name='total_price',
            field=models.CharField(default=100, max_length=300),
            preserve_default=False,
        ),
    ]
